### ISSUE TITLE
`report_record`.`count` tinyint range is too limited

### ISSUE THREAD

**Issue by jeanpaulgalea** [msimerson/mail-dmarc#100]
Hello,

Is there a specific reason why the `count` field [1] is `tinyint unsigned`? In MySQL [2] the range for that is only 0-255.

I've ran into a bug when we received reports with count value of 400 or more, which causes an INSERT error due to the limited range. We're running MariaDB 10.1.x with a bunch of options to force traditional SQL, escalating truncation warnings to errors and so on. Not sure if default MySQL installs have this problem, it might be that the value is silently truncated to 255.

I haven't had time to actually patch and test it, but I would be happy to if you are willing to merge this upstream.

Cheers and thanks for the software!

[1] https://github.com/jeanpaulgalea/mail-dmarc/blob/master/share/mail_dmarc_schema.mysql#L236
[2] https://dev.mysql.com/doc/refman/5.7/en/integer-types.html

**Comment by msimerson** [comment]
A PR is welcome.
