### ISSUE TITLE
save_aggregate in DMARC.pm fails when provided with DKIM verifier object.

### ISSUE THREAD

**Issue by djugessur** [msimerson/mail-dmarc#106]
I have run into a problem when I provide the dmarc object with the DKIM verifier object in line 259 in DMARC.pm.  $self->dkim does not exist.  If I provide the dmarc object with and explicit array of dkim results however there is no problem.

...
my $dmarc = Mail::DMARC::PurePerl->new();
my $dkim = Mail::DKIM::Verifier->new();

$dmarc->source_ip('127.0.0.1');
$dmarc->envelope_to('yahoo.ca');
$dmarc->envelope_from('yahoo.ca');
$dmarc->header_from('yahoo.ca');

my $fh;	
open($fh, "<:raw", $filename)
	or return("Can't open file $filename");

$dkim->load($fh);
$dkim->CLOSE;
$dmarc->dkim($dkim);   <--- this does not work, while $dmarc->dkim(domain => 'yahoo.ca', result => 'fail'); this does.

...
my $dmarcResult = $dmarc->validate(); <--- croaks if I use dkim verifier directly.

**Comment by msimerson** [comment]
My first guess: don't you need to call `$dkim->result;` first? After all, DMARC is evaluating the DKIM results, and your verifier doesn't yet have any results. Have a look at [the dkim parsing code](https://github.com/msimerson/mail-dmarc/blob/master/lib/Mail/DMARC.pm#L112-L133) and then compare that to what you're passing in.

**Comment by djugessur** [comment]
Sorry, I was calling $dkim->result;  The issue happens when there are no dkim signatures present in the message that's sent to DKIM.  $dkim->signatures is empty.

**Comment by msimerson** [comment]
Can you dump that Mail::DKIM::Verifier object at the point when you're passing it into Mail::DMARC?

**Comment by msimerson** [comment]
Also, if Mail::DMARC is croaking, what's the message it throws?

**Comment by djugessur** [comment]
croak "dkim argument not a ref" if ! ref $dkim;  in DKIM.pm is called when:

 push @{ $self->{dkim}},
        Mail::DMARC::Report::Aggregate::Record::Auth_Results::DKIM->new(@args); is being called in Auth_Results.pm.  Note that self->{dkim} is empty.

I'm a bit of a perl noob so bear with my while I figure out how to dump the dkim object.

**Comment by msimerson** [comment]
```perl
use Data::Dumper;
warn Dumper($dkim);
```

**Comment by djugessur** [comment]
Start dkim
$VAR1 = bless( {
                 'header_field_names' => [
                                           'received',
                                           'x-modus-reversedns',
                                           'x-modus-blacklist',
                                           'x-modus-rbl',
                                           'x-modus-trusted',
                                           'x-modus-spam-version',
                                           'subject',
                                           'from',
                                           'to'
                                         ],
                 'result' => 'none',
                 'buf_ref' => \'',
                 'signatures' => [],
                 'algorithms' => [],
                 'in_header' => 0,
                 'headers_by_name' => {
                                        'x-modus-reversedns' => ' OK

',
                                        'subject' => ' Legitimate message 1

',
                                        'received' => ' from  (localhost [127.0.0.1]) by DEV-DJ4.vircom.com

 (Vircom SMTPRS 6.4.110.21497/1049.7.4.) with SMTP id <B0002028958@DEV-DJ4.vircom.com> for <test2@testdomain.vc>;

 Mon, 20 Feb 2017 11:03:03 -0500

',
                                        'x-modus-rbl' => ' 127.0.0.1=OK

',
                                        'x-modus-trusted' => ' 127.0.0.1=NO

',
                                        'from' => ' <test@testdomain.vc>

',
                                        'x-modus-spam-version' => ' 6.4.110.21497/1049.7.4.

',
                                        'to' => ' <test@testdomain.vc>

',
                                        'x-modus-blacklist' => ' 127.0.0.1=OK;test@testdomain.vc=OK

'
                                      },
                 'headers' => [
                                'Received: from  (localhost [127.0.0.1]) by DEV-DJ4.vircom.com

 (Vircom SMTPRS 6.4.110.21497/1049.7.4.) with SMTP id <B0002028958@DEV-DJ4.vircom.com> for <test2@testdomain.vc>;

 Mon, 20 Feb 2017 11:03:03 -0500

',
                                'X-Modus-ReverseDNS: OK

',
                                'X-Modus-BlackList: 127.0.0.1=OK;test@testdomain.vc=OK

',
                                'X-Modus-RBL: 127.0.0.1=OK

',
                                'X-Modus-Trusted: 127.0.0.1=NO

',
                                'X-Modus-Spam-Version: 6.4.110.21497/1049.7.4.

',
                                'Subject: Legitimate message 1

',
                                'From: <test@testdomain.vc>

',
                                'To: <test@testdomain.vc>

'
                              ]
               }, 'Mail::DKIM::Verifier' );
$VAR1 = undef;

**Comment by djugessur** [comment]
An easier way to repro might be to just load a simple email msg that has no dkim headers into dkim.  Dkim returns a result of 'none' correctly but when this dkim verifier object is passed to the dmarc object, there are problems when aggregating reports.

**Comment by msimerson** [comment]
Does this diff fix the problem for you?

```diff
diff --git a/lib/Mail/DMARC.pm b/lib/Mail/DMARC.pm
index 2d68bda..69e397a 100644
--- a/lib/Mail/DMARC.pm
+++ b/lib/Mail/DMARC.pm
@@ -117,6 +117,7 @@ sub _from_mail_dkim {
         next if ref $s eq 'Mail::DKIM::DkSignature';
 
         my $result = $s->result;
+        next if !$result;
 
         if ($result eq 'invalid') {  # See GH Issue #21
             $result = 'temperror';
```

**Comment by djugessur** [comment]
No as $dkim->signatures is empty so the added line is not executed.

foreach my $s ( $dkim->signatures ) {
        next if ref $s eq 'Mail::DKIM::DkSignature';

        my $result = $s->result;
        next if !$result;

**Comment by msimerson** [comment]
I think I've found, thanks to your report, the underlying issue. I think I also have the cure:

```diff
diff --git a/lib/Mail/DMARC.pm b/lib/Mail/DMARC.pm
index 3ee2fbe..4ef6a7c 100644
--- a/lib/Mail/DMARC.pm
+++ b/lib/Mail/DMARC.pm
@@ -112,9 +112,12 @@ sub dkim {
 sub _from_mail_dkim {
     my ( $self, $dkim ) = @_;
 
+    my $signatures = 0;
+
     # A DKIM verifier will have result and signature methods.
     foreach my $s ( $dkim->signatures ) {
         next if ref $s eq 'Mail::DKIM::DkSignature';
+        $signatures++;
 
         my $result = $s->result;
 
@@ -130,6 +133,15 @@ sub _from_mail_dkim {
                 human_result => $s->result_detail,
             );
     }
+
+    if ($signatures < 1) {
+        push @{ $self->{dkim}},
+            Mail::DMARC::Report::Aggregate::Record::Auth_Results::DKIM->new(
+                domain       => $s->domain,
+                result       => 'none',
+            );
+    }
+
     return;
 }
 
@@ -269,7 +281,7 @@ sub save_aggregate {
 
     $agg->record($rec);
     return $self->report->save_aggregate;
-};
+}
 
 sub init {
     # used for testing
```
