### ISSUE TITLE
mail-dmarc.ini don't offer a port setting for the imap server

### ISSUE THREAD

**Issue by andreasschulze** [msimerson/mail-dmarc#118]
lib/Mail/DMARC/Report/Receive.pm assume port 993 if IO::Socket::SSL is installed.
that's no true for my host: I use IMAP on port 143 only.

I solved that by changing lib/Mail/DMARC/Report/Receive.pm, line 29
my $port   = defined $self->config->{imap}{port} ? $self->config->{imap}{port} : $self->get_imap_port();

that allow setting "port = 143" in /etc/mail-dmarc.ini

yes, that does not express encryption should be used or not. But in my case I limit the connection to localhost so plaintext don't hurt :-)

Andreas

**Comment by msimerson** [comment]
Sorry, TLS everywhere fan here. I'd prefer to make it more painful to use port 143 than for the admin to generate a self-signed certificate and use port 993.

**Comment by andreasschulze** [comment]
ok
