### ISSUE TITLE
metacharacters produce FN validation

### ISSUE THREAD

**Issue by qzrrbz** [msimerson/mail-dmarc#121]
```perl
sub is_valid_p {
    my ( $self, $p ) = @_;
    croak "unspecified p" if !defined $p;
    return ( grep {/^$p$/i} qw/ none reject quarantine / ) ? 1 : 0;
}
```
can be spoofed with `"v=DMARC1; p=.*"`

not that that is of any real value, but the idea of modding the pattern /^$x$/ to /^\Q$x\E$/ is what's intended here.

**Comment by msimerson** [comment]
looks like the same applies to:
- [ ] is_valid_rf
- [ ] aspf
- [ ] adkim

**Comment by qzrrbz** [comment]
as well as:
    fo
