### ISSUE TITLE
Domains listed in public_suffix_list fail to align

### ISSUE THREAD

**Issue by marcbradshaw** [msimerson/mail-dmarc#125]
@msimerson could I have your opinion on something please,

We had a ticket today relating to emails from 1password.com which were failing dmarc despite having a dkim signature from 1password.com.

These were failing because 1password.com is listed in the PRIVATE section of the public suffix list, and Mail::DKIM::PurePerl->is_dkim_alligned() has a check for is_public_suffix(), noting section 4.3.1 of the spec.

From the rfc it is clear that we shouldn't be stopping before a psl listed domain when finding an org domain, but it is ambiguous as to wether psl listed domains can be aligned with a direct match.

Clearly, in this case it is reasonable for 1password.com to be aligned as the signature domain and from domain match, the same would be true for any domain in the PRIVATE section.

For domains in the ICANN section it is less clear, there shouldn't really be a case in practice where an ICANN psl listed domain can sign, so there should never be an alignment, we still stop at the correct boundary, so I can't see any issue with dropping the check in is_dkim_aligned(), but it may be worth keeping that check for ICANN domains, and relaxing it for PRIVATE domains, however the amount of work in that is higher than dropping the check altogether.

What is your preferred solution, drop the check and allow psl listed domains to align when there is a direct match, or split the check and only allow alignment for domains listed in the PRIVATE section?

Thanks,
-Marc

**Comment by msimerson** [comment]
>  allow psl listed domains to align when there is a direct match

This seems plenty reasonable. The point of the DKIM signature is to validate the sender has control over the domain they purport to be sending from. In the case of an exact match, everything is as it should be.

> split the check and only allow alignment for domains listed in the PRIVATE section

This is a rather larger fork in the logic, and it requires grokking the semantics of the PSL. Not having to document/explain this condition seems reason enough to choose the former solution.
