### ISSUE TITLE
dmarc_update_public_suffix_list ignores file location specified in mail-dmarc.ini

### ISSUE THREAD

**Issue by ghost** [msimerson/mail-dmarc#136]
reading

https://metacpan.org/pod/distribution/Mail-DMARC/bin/dmarc_update_public_suffix_list

> To download a new Public Suffix List to the location specified my mail-dmarc.ini

In my config
```
cat /usr/local/etc/auth-milter/mail-dmarc.ini
	...
	[dns]
	timeout            = 5
	public_suffix_list = /usr/local/etc/auth-milter/public_suffix_list
	...
```

When I exec
```
dmarc_update_public_suffix_list --config-file=/usr/local/etc/auth-milter/mail-dmarc.ini
```

it's not creating/updating the .ini-file-specified public_suffix_list

instead, it returns
```
Public Suffix List file /usr/lib/perl5/site_perl/5.26.1/auto/share/dist/Mail-DMARC/public_suffix_list not modified
```

checking
```
ls -al \
 /usr/lib/perl5/site_perl/5.26.1/auto/share/dist/Mail-DMARC/public_suffix_list \
 /usr/local/etc/auth-milter/public_suffix_list
	ls: cannot access '/usr/local/etc/auth-milter/public_suffix_list': No such file or directory
	-r--r--r-- 1 root root 204K Oct 10 08:33 /usr/lib/perl5/site_perl/5.26.1/auto/share/dist/Mail-DMARC/public_suffix_list
```

**Comment by msimerson** [comment]
The file you specified doesn't exist. See your `checking` block:

`ls: cannot access '/usr/local/etc/auth-milter/public_suffix_list': No such file or directory`

The PSL loader tries to load the file you specify in your config. If that fails (file doesn't exist or not readable) it falls back to the included PSL.
