### ISSUE TITLE
IdentifierType 'envelope_from' missing when SPFDomainScope is 'helo'

### ISSUE THREAD

**Issue by freddieleeman** [msimerson/mail-dmarc#141]
I've been processing quite some DMARC reports and I've noticed that the Mail::DMARC report generator is the most RFC compliant generator publicly available. The only time the reports fail validation is when a record's SPFDomainScope has a 'helo' value. These records fail validation because the 'envelope_from' element is missing which has a minOccurs of 1.

Both Fastmail and SpamTitan are the largest suppliers of reports I've processed that use Mail::DMARC and about 3% of the reports do not comply with RFC guidelines because of the missing envelope_from element in some of the records.

**Comment by msimerson** [comment]
This likely happens when the SMTP session terminates after `HELO` and before `MAIL FROM: ...`. In such a case, there is no `envelope_from` to report. It's been a while since I read the RFC but I don't recall it specifying what to put there in such a case.

Suggestions?

**Comment by freddieleeman** [comment]
I've concluded that this isn't caused by a termination of the SMTP session but rather by null reverse-path messages like non-delivery notifications, delivery status notifications and message disposition
notifications.

Also see my message in the DMARC IETF WG: https://mailarchive.ietf.org/arch/msg/dmarc/Ql4WHQ_lbTZ3-ZziXEm_yBBgaKY

My suggestion for now would be to add the element to the XML but allow it to be empty whenever the SMTP session has a null reverse-path. At least until more specific guidelines are agreed upon by the IETF WG.

**Comment by msimerson** [comment]
> My suggestion for now would be to add the element to the XML but allow it to be empty

Seems reasonable to me. PR is welcome.

**Comment by msimerson** [comment]
This patch *might* do the needful. Some testing would be appreciated.

```diff
diff --git a/lib/Mail/DMARC/Report/Aggregate.pm b/lib/Mail/DMARC/Report/Aggregate.pm
index acd4983..3e4b11d 100644
--- a/lib/Mail/DMARC/Report/Aggregate.pm
+++ b/lib/Mail/DMARC/Report/Aggregate.pm
@@ -93,10 +93,16 @@ sub get_identifiers_as_xml {
     my ( $self, $rec ) = @_;
     my $id = "\t\t<identifiers>\n";
     foreach my $f (qw/ envelope_to envelope_from header_from /) {
-        if ( $f eq 'header_from' && ! $rec->{identifiers}{$f} ) {
-            croak "missing header_from!";
+        if ( $f eq 'header_from' ) {        # min occurs = 1
+            croak "missing header_from!" if ! $rec->{identifiers}{$f};
+        }
+        elsif ( $f eq 'envelope_from') {    # min occurs = 1
+            $rec->{identifiers}{$f} = '' if ! $rec->{identifiers}{$f};
+        }
+        elsif ( $f eq 'envelope_to' ) {     # min occurs = 0
+            next if ! $rec->{identifiers}{$f};
         };
-        next if !$rec->{identifiers}{$f};
+
         my $val = XML::LibXML::Text->new( $rec->{identifiers}{$f} )->toString();
         $id .= "\t\t\t<$f>$val</$f>\n";
     }
```
