### ISSUE TITLE
Use of uninitialized value in dmarc_send_reports and Aggregate.pm

### ISSUE THREAD

**Issue by freddieleeman** [msimerson/mail-dmarc#156]
Have seen a couple of these while logging version `v1.20191004`:

```
Domain: <hidden>
Use of uninitialized value in concatenation (.) or string at /usr/local/bin/dmarc_send_reports line 105.
rua:
Use of uninitialized value $reco in concatenation (.) or string at /usr/local/share/perl/5.28.1/Mail/DMARC/Report/Aggregate.pm line 65.
No valid ruas found, deleting report

Domain: <hidden>
rua:
No valid ruas found, deleting report
sleeping 5.Use of uninitialized value in concatenation (.) or string at /usr/local/bin/dmarc_send_reports line 105.
Use of uninitialized value $reco in concatenation (.) or string at /usr/local/share/perl/5.28.1/Mail/DMARC/Report/Aggregate.pm line 65.
```
The `rua:` value in the verbose output appears to be empty but the domains do have a rua tag specified.

**Comment by msimerson** [comment]
> The rua: value in the verbose output appears to be empty but the domains do have a rua tag specified.

The RUA may be specified, but is it syntactically correct?  If it fails to parse, that would result in the error you're seeing.

**Comment by freddieleeman** [comment]
I seem to have misplaced the original log and am unable to validate the original rua value. I will however keep an eye out if I ever notice the same error again and will then validate the rua value. We notice a lot of people publish a DMARC record without the 'mailto:' prefix in the rua value. Maybe that was the case in this situation as well.

**Comment by freddieleeman** [comment]
Haven't seen this issue in a long time. Closing
