### ISSUE TITLE
SQLite tests failing

### ISSUE THREAD

**Issue by rjbs** [msimerson/mail-dmarc#16]
```
~/.cpanm/work/1420752724.36287/Mail-DMARC-1.20141230$ perl -Mblib t/12.Report.Store.SQL.t
ok 1 - use Mail::DMARC::Report::Store::SQL;
ok 2 - An object of class 'Mail::DMARC::Report::Store::SQL' isa 'Mail::DMARC::Report::Store::SQL'
ok 3 - db_connect
ok 4 - An object of class 'DBIx::Simple' isa 'DBIx::Simple'
ok 5 - query_insert, report, 1
not ok 6 - query_delete
```

...and so on, but that's the only failure.

I am using DBD::SQLite 1.31 on perl 5.8.8.

**Comment by rjbs** [comment]
The issue is DBIx::Simple.  DBIx::Simple 1.35 is the earliest version with which this test passes — it's also the newest version available at the moment.  Please just update the required version. :)

**Comment by msimerson** [comment]
Done, thanks for debugging.
