### ISSUE TITLE
distribution missing in CPAN

### ISSUE THREAD

**Issue by fany** [msimerson/mail-dmarc#162]
Hi,

when looking for its documentation on [meta::cpan](https://metacpan.org/release/Mail-DMARC) today, I found out that Mail::DMARC is currently not in CPAN.
(I'm quite sure it had been there in November, because meta::cpan says I added it to my favorites then.)

Is this intended?
Is Mail::DMARC supposed to reappear anytime soon?
If not, can you suggest a replacement?

I ask because my own CPAN module [Mail::Qmail::Filter::DMARC](https://metacpan.org/pod/Mail::Qmail::Filter::DMARC) currently depends on Mail::DMARC::PurePerl.

Kind regards
Martin

**Comment by msimerson** [comment]
Hmmm, I deleted the most recent version of Mail::DMARC from PAUSE, due to #155. Interestingly, that caused it to be removed from meta::cpan. Perhaps that's a bug in meta::cpan that needs addressing. I'll get a new version published soon.

**Comment by fany** [comment]
Thanks for your quick and informative reply!

I don't think it's a meta::cpan specific problem, though, since `CPAN.pm` also currently does not find Mail::DMARC:
```
cpan[1]> reload index
Reading '/root/.cpan/Metadata'
  Database was generated on Wed, 08 Jan 2020 06:55:37 GMT
Fetching with LWP:
http://www.cpan.org/authors/01mailrc.txt.gz
Reading '/root/.cpan/sources/authors/01mailrc.txt.gz'
............................................................................DONE
Fetching with LWP:
http://www.cpan.org/modules/02packages.details.txt.gz
Reading '/root/.cpan/sources/modules/02packages.details.txt.gz'
  Database was generated on Wed, 08 Jan 2020 21:17:03 GMT
............................................................................DONE
Fetching with LWP:
http://www.cpan.org/modules/03modlist.data.gz
Reading '/root/.cpan/sources/modules/03modlist.data.gz'
DONE
Writing /root/.cpan/Metadata


cpan[2]> look Mail::DMARC
Warning: Cannot look Mail::DMARC, don't know what it is.
```

**Comment by msimerson** [comment]
I don't know what the issue is, but when I look in PAUSE, all the previous releases of Mail::DMARC are still there. 🤷‍♂️
