### ISSUE TITLE
Optionally DKIM sign outgoing reports.

### ISSUE THREAD

**Issue by marcbradshaw** [msimerson/mail-dmarc#17]
Considering adding support for DKIM signing the outgoing reports.

**Comment by marcbradshaw** [comment]
@msimerson 

I have some code in my fastmail/dkim_sign branch to do this now.

How do you feel about adding the Mail::DKIM dependency? I could make it an optional require if the relevant section of config is defined.

Still have some error handling to add, so no pull request as yet.

**Comment by msimerson** [comment]
1. it's a great feature and I'm glad you've doing it, thank you.
2. I'm a big fan of graceful degradation. Use a stringy eval to determine if Mail::DKIM is available (once, not often) and if so, enable the feature.
3. I dislike modules that install 3/4 of CPAN to work.
