### ISSUE TITLE
requirement of mail-dmarc.ini is undocumented (or underdocumented)

### ISSUE THREAD

**Issue by rjbs** [msimerson/mail-dmarc#18]
I couldn't use Mail::DMARC until I make a 0b file called `mail-dmarc.ini` and pointed at it.  I only learned this by getting an exception when it didn't exist and then reading the source.

**Comment by rjbs** [comment]
I'm not sure this commit will really help all that much.  In general, I don't think CPAN users (certainly not myself) read the INSTALL document, because INSTALL gets done by a CPAN client.  After that has happened, the INSTALL file is thrown away, so there is nothing to point back at this.

The `config_file` option is not documented at all, for example, nor is the set of data expected to be in the file.

If the default configuration is sufficient for most uses, another option would be to install the file to a "share dir," and add the distribution's share dir to the path searched for the file as a last option, using File::ShareDir.

At any rate, I've sorted out how to deal with this locally, but for future users, I think that this commit won't be enough.

**Comment by msimerson** [comment]
If someone is installing Mail::DMARC to use only as a validator, then installing a default .ini in the sharedir would be a perfectly fine solution for them. If they want to enable reporting, then they really will need to get a mail-dmarc.ini file customized with local settings.

TODO:
1. Install mail-dmarc.ini in sharedir
2. Add sharedir to the  list of locations searched for mail-dmarc.ini
3. when attempting to report, check for default values in config and bark very loudly, preferably providing instructions on how to install mail-dmarc.ini.

**Comment by msimerson** [comment]
I have [added mail-dmarc.ini to the ShareDir](https://github.com/msimerson/mail-dmarc/commit/f5ed8120a5bd4f48bfe12e67f4609122d72d9d6d?diff=unified), mostly resolving this issue.
