### ISSUE TITLE
spamassassin 4 fails to make dmarc repots

### ISSUE THREAD

**Issue by xpunkt** [msimerson/mail-dmarc#211]
Mar 23 05:54:55 localhost spamd[4127]: DMARC: report could not be saved: DBI connect('dbname=dmarc_reports.sqlite','',...) failed: unable to open database file at /usr/lib64/perl5/vendor_perl/5.36/Mail/DMARC/Report/Store/SQL.pm line 551.

[report_store]
backend = SQL
dsn = dbi:Pg:dbname=dmarc;host=127.0.0.1;port=5432;
user = user
pass = pass
auto_save = 0

help me resolve this

if its Mail::DMARC fail then i am here :)

but i fear its a spamassassin fail, since imap import reports works

**Comment by xpunkt** [comment]
i found the problem :)

in gentoo i did /etc/dmarc with have all config and data files, it worked as designed if i just cd /etc/dmarc before i called any shell tools :)

solotion was to move mail-dmarc.ini to /etc :)

can this be confirmed ?

**Comment by msimerson** [comment]
That is what the [INSTALL](https://github.com/msimerson/mail-dmarc/blob/master/INSTALL.md) document says to do.
