### ISSUE TITLE
Is Net::SSLeay used ?

### ISSUE THREAD

**Issue by mirespace** [msimerson/mail-dmarc#215]
Hi!

I'm working in the libmail-dmarc-perl package on Ubuntu to make it available from main repository (nowadays it's in universe). 

While reviewing the dependencies, I see Net::SSLeay declared in 'requires' in the META files, Makefile.PL and Build.PL. But, I don't see that module referenced or used anywhere else.

I did a built without it and the tests passed, but I would like to have your opinion on this: could it be removed from the dependencies?

Thanks in advance.

**Comment by msimerson** [comment]
`Net::SSLeay` is used by `HTTP::Tiny`, which is used to download updated PSL files from a `https` location.
