### ISSUE TITLE
Unable to view backends in ./t/travis/backends

### ISSUE THREAD

**Issue by eserte** [msimerson/mail-dmarc#226]
Mail-DMARC-1.20240313 fails on all of my smoker systems like this:
```
Unable to view backends in ./t/travis/backends at t/12.Report.Store.SQL.t line 49.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 2.
t/12.Report.Store.SQL.t ...................... 
Dubious, test returned 2 (wstat 512, 0x200)
All 2 subtests passed 
```

**Comment by marcbradshaw** [comment]
That directory does appear to be missing from the tarball when I run make dist, @msimerson any ideas?

**Comment by msimerson** [comment]
My bad!  I added it to MANIFEST.SKIP. 😬

I was cleaning out the leftovers from Travis CI and didn't notice those are test fixtures. I'll restore them.

**Comment by msimerson** [comment]
We should be good now. It's late o'clock in my world. If Marc doesn't beat me to it, I'll roll a new release tomorrow that should fix the issue.
