### ISSUE TITLE
Report parsing failure: ":1: parser error : Start tag expected, '<' not found"

### ISSUE THREAD

**Issue by richlv** [msimerson/mail-dmarc#247]
**Describe the bug**
Reports from gmx.net are not parsed.
Cannot share the original report unfortunately, but happy to perform debugging.

Saving the attachment from the email produces valid gzipped XML.
base64-decoding the attachment also produces a valid gzipped XML.

**To Reproduce**
1. Get a report from gmx.de
2. dmarc_receive it

**Expected behavior**
Parsed as others.

**Server (please complete the following information):**
 - OS: OpenSUSE
 - Tumbleweed

**Perl (please complete the following information):**
 - Version v5.40.0

**Comment by richlv** [comment]
The string, printed in the error message, might correspond to hex `ef bf bd`.

**Comment by richlv** [comment]
The zip content type apparently was in error and was fixed on the GMX side.
Perhaps additional validation could be done - and the `verbose` flag documented / added in `--help`?

**Comment by msimerson** [comment]
There's an infinite number of ways reports can fail to adhere to the DMARC specification. I think trying to guard against them is not a good use of my time, but I would happily consider a PR that implements your suggestions.

**Comment by richlv** [comment]
Thank you so much for looking into this. What about the undocumented `-v` flag, could that be handled in this issue, or would a new one be preferred?

**Comment by msimerson** [comment]
No need for an open issue, a PR is preferred.
