### ISSUE TITLE
are resources being initialized more often than needed?

### ISSUE THREAD

**Issue by rjbs** [msimerson/mail-dmarc#38]
While looking at something else, I noticed the PSL being loaded more frequently than I expected.  It's initialized in `is_public_suffix` in Mail::DMARC::Base, and stored in `$self->{public_suffixes}`.  This comment is in there:

```perl
    # load PSL into hash for fast lookups, esp. for long running daemons
    my %psl = map { $_ => 1 }
              grep { $_ !~ /^[\/\s]/ } # weed out comments & whitespace
              map { chomp($_); $_ }    # remove line endings
              <$fh>;
```

…but as near as I can tell, the hash isn't persistent for long running daemons.  I might be wrong about that, in which case please let me know what I missed and close the ticket!

If I'm not wrong, though, I think the issue is the dual purpose of Mail::DMARC objects.  They are both validators and validation state objects.  What I had expected to see was a reusable validator object which accepted requests and provided results.  That way, the validator could be initialized once and run forever, reusing its components (which could include its resolver, a PSL, and so on).

I looked at Mail::DMARC::HTTP, and I found that (for example) `serve_validator` seems to create a new Mail::DMARC::PurePerl object for each request, meaning that each request will reparse the PSL, initialize a new DNS resolver, and so on.

Have I misunderstood?  If not, do we want to address this?

**Comment by msimerson** [comment]
This should be pretty easy to write some tests for and make sure that it's doing The Right Thing today, and that it continues to in the future. I'll have a look when I get some spare cycles.

**Comment by msimerson** [comment]
I inserted a warning line inside the block of code that loads the PSL, and then restarted dmarc_httpd and watched a few connections:

````
Resolved [*]:8080 to [0.0.0.0]:8080, IPv4
Binding to TCP port 8080 on host 0.0.0.0 with IPv4
Group Not Defined.  Defaulting to EGID '1001 1001 0 20'
User Not Defined.  Defaulting to EUID '1000'
  Dispatch: / => CODE(0x80823de88)
path: /dmarc/json/validate
loading Public Suffix List
path: /dmarc/json/validate
path: /dmarc/json/validate
````

I'm not sure what you missed, but you missed it. :)

**Comment by msimerson** [comment]
Hmmm, I make have spoke too soon:
````
loading Public Suffix List
path: /dmarc/json/validate
path: /dmarc/json/validate
path: /dmarc/json/validate
path: /dmarc/json/validate
path: /dmarc/json/validate
loading Public Suffix List
path: /dmarc/json/validate
loading Public Suffix List
path: /dmarc/json/validate
loading Public Suffix List
path: /dmarc/json/validate
path: /dmarc/json/validate
loading Public Suffix List
path: /dmarc/json/validate
loading Public Suffix List
path: /dmarc/json/validate
path: /dmarc/json/validate
````
Now, as to why it's loading more often than needed, I'm uncertain.

**Comment by rjbs** [comment]
I'm laid up sick today, so forgive me if it turns out I'm writing this whilst hallucinating.

What I don't see is why this would *not* always be reloading.  I'm going to walk through the code a bit.

Net::DMARC::HTTP dispatches every request (in its `if ($path)` branch) to a routine with no access back to `$self`, so the HTTP daemon itself can store no state.  Validations go to `serve_validator`.

If there are no errors, then `serve_validator` will always create a Mail::DMARC::PurePerl object and call its `validate` method.  The object is stored in a local variable and not cached or closed over that I can see.

`validate` will call `exists_in_dns` if it can figure out a domain from From.  `exists_in_dns` will call `get_organizational_domain`, which will call `is_public_suffix`.  That's defined in Mail::DMARC::Base.

`is_public_suffix` *does* cache the public suffix list.  It stores it in `$self`, which in this call chain would be the Mail::DMARC::PurePerl object created in the HTTP.  That means the cache would have the life span of exactly one request.  

It seems unlikely that you'd feed the test server a lot of cases and for minutes get only requests that bail out before calling `is_public_suffix`, but I don't see another obvious way that this would be cached.

**Comment by msimerson** [comment]
So, the reason I saw more than one loading of the PSL is actually fairly easy to explain: Net::Server::PreFork.
````
11025  0  SJ   0:00.61 /usr/bin/perl ./bin/dmarc_httpd (perl5.18.4)
11031  0  SJ   0:00.08 /usr/bin/perl ./bin/dmarc_httpd (perl5.18.4)
11033  0  SJ   0:00.07 /usr/bin/perl ./bin/dmarc_httpd (perl5.18.4)
14682  0  SJ   0:00.06 /usr/bin/perl ./bin/dmarc_httpd (perl5.18.4)
14920  0  SJ   0:00.00 /usr/bin/perl ./bin/dmarc_httpd (perl5.18.4)
14974  0  SJ   0:00.00 /usr/bin/perl ./bin/dmarc_httpd (perl5.18.4)
````
Merging @marcbradshaw 's PR didn't fully solve the problem because if we want to only load the PSL once, then we **must** load it before Net::Server::HTTP forks. Moving the $dmarc object creating out of Mail::DMARC::HTTP into the dmarc_httpd exe, loading up the PSL, and then passing in a $report object solves it nicely. A PR will arrive soon.
