### ISSUE TITLE
Handle invalid DMARC records optimally

### ISSUE THREAD

**Issue by msimerson** [msimerson/mail-dmarc#39]
Whether because of [PEBKAC](http://en.wikipedia.org/wiki/User_error#Acronyms_and_other_names),  DNS truncation (see #20), or phase of moon, DMARC records arrive via DNS that aren't valid. Our intention is to do the best we can with what we get. Please use this issue to report such observed specimens. The developers will add [tests to Mail::DMARC::Policy](https://github.com/msimerson/mail-dmarc/blob/master/t/01.Policy.t) to assure we are being liberal in what we accept, thereby honoring Jon Postel's Law / aka the [Robustness Principle](https://en.wikipedia.org/wiki/Robustness_principle).

**Comment by marcbradshaw** [comment]
domain=edm.groceryrun.com.au;v=dmarc1;p=none;rua=mailto:dmarc_feedback@inxmail.de&amp;amp;amp;amp;lt;dmarc_feedback@inxmail.de&amp;amp;amp;amp;gt

;; ANSWER SECTION:
_dmarc.edm.groceryrun.com.au. 647 IN	TXT	"v=dmarc1\; p=none\; rua= mailto:dmarc_feedback@inxmail.de &amp\;amp\;amp\;amp\;lt\;dmarc_feedback@inxmail.de&amp\;amp\;amp\;amp\;gt\;"

**Comment by marcbradshaw** [comment]
domain=e.accuquote.com;v=DMARC1;p=none;fo:0;adkim=r;aspf=r;sp=none;rua=mailto:accu_postmaster@accuquote.com

**Comment by marcbradshaw** [comment]
domain=targetselect.net;v=DMARC1;p=none;rua=mailto:postmaster@targetselect.net;ruf=mailto:postmaster@targetselect.net;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none

;; ANSWER SECTION:
_dmarc.targetselect.net. 78077	IN	TXT	"v=DMARC1\; p=none\; rua=mailto:postmaster@targetselect.net\; ruf=mailto:postmaster@targetselect.net\; adkim=r\; aspf=r\; pct=100\; rf:" "afrf\; ri=86400\; sp=none"

**Comment by marcbradshaw** [comment]
domain=1105insight.com;v=DMARC1;p=none;rua=mailto:postmaster@1105insight.com;ruf=mailto:postmaster@1105insight.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none

domain=borsheims.net;v=DMARC1;p=none;rua=mailto:postmaster@borsheims.net;ruf=mailto:postmaster@borsheims.net;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none

domain=caasco.ca;v=DMARC1;p=none;sp=none;rua=mailto:dmarc_agg@auth.returnpath.net;ruf=mailto:dmarc_afrf@auth.returnpath.net;rf=afrf;pct100

domain=consumersilver.com;v=DMARC1;p=none;rua=mailto:postmaster@consumersilver.com;ruf=mailto:postmaster@consumersilver.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none

domain=coppermail-usa.com;v=DMARC1;p=none;rua=mailto:postmaster@coppermail-usa.com;ruf=mailto:postmaster@coppermail-usa.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none

domain=eglancesender.com;v=DMARC1;p=none;rua=mailto:postmaster@eglancesender.com;ruf=mailto:postmaster@eglancesender.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none

domain=egroupconsumer.com;v=DMARC1;p=none;rua=mailto:postmaster@egroupconsumer.com;ruf=mailto:postmaster@egroupconsumer.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none

domain=eselectsender.com;v=DMARC1;p=none;rua=mailto:postmaster@eselectsender.com;ruf=mailto:postmaster@eselectsender.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none

domain=filemail.com;v=DMARC1;p=none;rua=mailto:admin@filemail.com;ruf=mailto:admin@filemail.com;fo:0;adkim=r;aspf=r

domain=fisherprograms.com;v=DMARC1;p=none;rua=mailto:postmaster@fisherprograms.com;ruf=mailto:postmaster@fisherprograms.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none

domain=mail-peninsula.com;v=DMARC1;p=none;rua=mailto:umesh@force24.co.uk;ruf=mailto:umesh@force24.co.uk;fo:0;adkim=r;aspf=r;pct=100;rf=afrf;ri=86000;sp=none

domain=reply.myphotobook.de;v=DMARC1;p=reject;adkim=s;aspf=r;rf�rf;pct0

domain=sendergroup.com;v=DMARC1;p=none;rua=mailto:postmaster@sendergroup.com;ruf=mailto:postmaster@sendergroup.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none

domain=targetselection.com;v=DMARC1;p=none;rua=mailto:postmaster@targetselection.com;ruf=mailto:postmaster@targetselection.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none

domain=theluxurycloset.info;v=DMARC1;p=reject;adkim=s;aspf=r;rf=afrf;;pct=100

domain=trondheim-redcross.no;v=DMARC1;p=none;rua=mailto:postmaster@trondheim-redcross.no;ruf=mailto:johess@trondheim-redcross.no;fo:0;adkim=r;aspf=r;pct=100;rf=afrf;ri=86400;sp=none

domain=vsender-2.com;v=DMARC1;p=none;rua=mailto:postmaster@vsender-2.com;ruf=mailto:postmaster@vsender-2.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none

domain=wfyi.org;v=DMARC1;p=none;rua=mailto:dmarc1630@wfyi.org;ruf=mailto:dmarc1630@wfyi.org;fo:0;adkim=r;aspf=r;pct=100;rf=afrf;ri=86400;sp=none

domain=wk1business.com;v=DMARC1;p=none;rua=mailto:postmaster@wk1business.com;ruf=mailto:postmaster@wk1business.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none

**Comment by marcbradshaw** [comment]
domain=edm.groceryrun.com.au;v=dmarc1;p=none;rua=mailto:dmarc_feedback@inxmail.de&amp;amp;amp;amp;lt;dmarc_feedback@inxmail.de&amp;amp;amp;amp;gt
domain=reply.myphotobook.de;v=DMARC1;p=reject;adkim=s;aspf=r;rf�rf;pct0
domain=teogenes.com.br;v=DMARC1;p=quarantine;rua=mailto:retorno@teogenes.com.br;fo:1:d;adkim=r;aspf=r;rf=afrf;sp=quarantine
domain=wkcplatnium.com;v=DMARC1;p=none;rua=mailto:postmaster@wkcplatnium.com;ruf=mailto:postmaster@wkcplatnium.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none

**Comment by marcbradshaw** [comment]
domain=accuquote.com;v=DMARC1;p=none;fo:0;adkim=r;aspf=r;sp=none;rua=mailto:accu_postmaster@accuquote.com
domain=brightworksgroup.net;v=DMARC1;p=none;0;adkim=r;aspf=r
domain=bronzemail-usa.com;v=DMARC1;p=none;rua=mailto:postmaster@bronzemail-usa.com;ruf=mailto:postmaster@bronzemail-usa.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none
domain=driveconsumer.com;v=DMARC1;p=none;rua=mailto:postmaster@driveconsumer.com;ruf=mailto:postmaster@driveconsumer.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none
domain=econnect1.com;v=DMARC1;p=none;rua=mailto:postmaster@econnect1.com;ruf=mailto:postmaster@econnect1.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none
domain=esender1.com;v=DMARC1;p=none;rua=mailto:postmaster@esender1.com;ruf=mailto:postmaster@esender1.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none
domain=esender3.com;v=DMARC1;p=none;rua=mailto:postmaster@esender3.com;ruf=mailto:postmaster@esender3.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none
domain=lns.com;v=DMARC1;p=none;rua=mailto:dmarc@lns.com;ruf=mailto:dmarc@lns.com;0;adkim=r;aspf=r;pct=100;rf=afrf;ri=86400;sp=none
domain=my-dear-lady.com;v=DMARC1;p=none;rua=mailto:postmaster@my-dear-lady.com;ruf=mailto:postmaster@my-dear-lady.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none
domain=newsletter.ironpony.net;v=DMARC1;p=none;rua=mailto:postmaster@newsletter.ironpony.net;ruf=mailto:postmaster@newsletter.ironpony.net;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none
domain=vsender-3.com;v=DMARC1;p=none;rua=mailto:postmaster@vsender-3.com;ruf=mailto:postmaster@vsender-3.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none

**Comment by marcbradshaw** [comment]
domain=aeukda.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=anxado.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=avribx.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=ayjiop.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=baayhv.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=beikaa.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=bprixr.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=diibdx.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=dujhfi.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=dwxaqq.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=eebrch.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=eesqpo.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=enmwvf.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=esender2.com;v=DMARC1;p=none;rua=mailto:postmaster@esender2.com;ruf=mailto:postmaster@esender2.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none
domain=esender4.com;v=DMARC1;p=none;rua=mailto:postmaster@esender4.com;ruf=mailto:postmaster@esender4.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none
domain=etgelw.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=eudrle.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=euzqht.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=eydpuv.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=hijutu.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=hzezbo.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=iafhia.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=iapjue.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=icdiww.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=igisvo.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=ihxhbw.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=iitwtb.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=ivaopy.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=jabrrb.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=kauawe.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=kdkxxa.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=kedkoe.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=lsecoj.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=lxlrzx.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=mhsvaa.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=nacrga.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=nhwdxr.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=nntmqa.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=oefoqs.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=ouhazn.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=peotfv.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=srxeba.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=tlcdoa.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=udixau.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=ufiipt.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=vopklo.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=wkmailer.com;v=DMARC1;p=none;rua=mailto:postmaster@wkmailer.com;ruf=mailto:postmaster@wkmailer.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none
domain=wtqwip.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=wueozx.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=yeakre.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=yodqno.perfecttrinityslaw.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.perfecttrinityslaw.net;ruf=mailto:dmarc@auth.perfecttrinityslaw.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net
domain=zfefbw.luckyalexsgroup.net;v=DMARC1;p=none;sp=none;rua=mailto:dmarc@auth.luckyalexsgroup.net;ruf=mailto:dmarc@auth.luckyalexsgroup.net;aspf=r;adkim=r;pct=0;perfecttrinityslaw.net

**Comment by marcbradshaw** [comment]
domain=rubymail-usa.com;v=DMARC1;p=none;rua=mailto:postmaster@rubymail-usa.com;ruf=mailto:postmaster@rubymail-usa.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none
domain=reply.garten-und-freizeit.de;v=DMARC1;p=reject;adkim=s;aspf=r;rf=afrf;pct=100;ldquo
domain=nlmx.hervis-sportsclub.cz;v=DMARC1;p=reject;adkim=s;aspf=r;rf=afrf;pct=100;"
domain=mapdotbusiness.com;v=DMARC1;p=none;rua=mailto:postmaster@mapdotbusiness.com;ruf=mailto:postmaster@mapdotbusiness.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none
domain=elpaseolimo.com;v=DMARC1;p=;rua=mailto:alerts@ccitech.com;ruf=mailto:alerts@ccitech.com;rf=afrf;pct=
domain=econnect3.com;v=DMARC1;p=none;rua=mailto:postmaster@econnect3.com;ruf=mailto:postmaster@econnect3.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none
domain=econnect4.com;v=DMARC1;p=none;rua=mailto:postmaster@econnect4.com;ruf=mailto:postmaster@econnect4.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none
domain=econnect5.com;v=DMARC1;p=none;rua=mailto:postmaster@econnect5.com;ruf=mailto:postmaster@econnect5.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none
domain=bizsourceinfo.com;v=DMARC1;p=none;rua=mailto:postmaster@bizsourceinfo.com;ruf=mailto:postmaster@bizsourceinfo.com;adkim=r;aspf=r;pct=100;rf:afrf;ri=86400;sp=none

**Comment by msimerson** [comment]
What I've noticed so far is that this change resolves the vast majority of parse failures:
```perl
--- a/lib/Mail/DMARC/Policy.pm
+++ b/lib/Mail/DMARC/Policy.pm
@@ -31,7 +31,7 @@ sub parse {
     my @tag_vals = split /;/, $str;
     my %policy;
     foreach my $tv (@tag_vals) {
-        my ($tag, $value) = split /=/, $tv, 2;
+        my ($tag, $value) = split /=|:/, $tv, 2;
         if ( !defined $tag || !defined $value || $value eq '') {
             warn "invalid DMARC record, please post this message to\n" .
                  "\thttps://github.com/msimerson/mail-dmarc/issues/39\n" .
```

**Comment by marcbradshaw** [comment]
That gets a large chunk of them yes.
The change looks good, can't think of a way it would break valid records. Would it still be worth warning on these ones? the records are still technically invalid.

**Comment by msimerson** [comment]
> can't think of a way it would break valid records

I've got some tests for it written and I don't see any opportunity for it to break valid records.

>  Would it still be worth warning on these ones?

Maybe a different warning, that doesn't ask for them to be reported. It'd probably be good to add a config option to shut up those warnings. No point in polluting peoples logs if they aren't going to do anything about the warnings.

**Comment by marcbradshaw** [comment]
A few more which don't match already reported patterns
`````
domain=cmnet.org;v=DMARC1;p=none;sp=none;rua=mailto:postmaster@cmnet.org!10m;;pct=100;ri=86400
domain=coachingcompass.com;v=DMARC1;p=quarantine;rua=mailto:dan@darau.com;ruf=mailto:dan@darau.com;1:d:s;adkim=r;aspf=r;rf=afrf;sp=quarantine
domain=email.ex.kbhmaui.com;v=DMARC1;p=none;rua=mailto:dmarc-reports@email.ex.kbhmaui.com;pct=100;”
domain=genetex.com;v=DMARC1;p=none;sp-none;rua=mailto:postmaster@genetex.com!1m;ruf=mailto:postmaster@genetex.com!1m;rf=afrf;pct=100;ri=86400

**Comment by msimerson** [comment]
* `;;` would be easy to filter out and skip emitting an error for.
* checking for and stripping off leading and trailing `"` also seems safe
* considering their proximity on the keyboard, allowing `-` to be a tolerable replacement for `=` also seems safe enough.

**Comment by tomkicamp** [comment]
Depending on just how tolerant of broken records you want to be, here are some other fairly common problems I've noticed:
p=monitor (should be 'none')
rua=dmarc@dmarctest.com (needs 'mailto:')
v=dmarc1 (per spec, must be uppercase DMARC1)

**Comment by msimerson** [comment]
I'm closing this issue because:
* recent changes will tolerate the vast majority of errors
* there's nothing else to do *for now*
* reporting can continue, and if we identify more common failures that deserve action, this can be reopened

**Comment by bigio** [comment]
$ dig +short txt _dmarc.viaggiailmondo.store
"v=DMARC1; p=none; rua=mailto:dmarc@be-mail.it; ruf=mailto:dmarc@be-mail.it; sp=none; aspf"

**Comment by hege-li** [comment]
domain=instant-iptv.net;v=DMARC1; p=none; pct=100; rua=mailto:postmaster@instant-iptv.net;  checkmark

**Comment by hege-li** [comment]
dig +short txt _dmarc.ospedalerc.it
"v=DMARC1; p=none; sp=none; fo=; ri=3600; rua=mailto:dmarca@ospedalerc.it; ruf=mailto:dmarcf@ospedalerc.it"

**Comment by freddieleeman** [comment]
domain=seta.net;v=DMARC1;p=none;pct100;rua=mailto:dmarc_rua@emrl.com;ruf=mailto:dmarc_ruf@emrl.com

**Comment by Philippe23** [comment]
invalid DMARC record noted in my SpamAssassin 4.0 logs:
```
domain=mutualart.com;v=DMARC1; p=none; rua=; ruf=; fo=1
```

**Comment by Philippe23** [comment]
invalid DMARC record noted in my SpamAssassin 4.0 logs:
```
domain=advisortohr.com;v=DMARC1; p=none; rua=mailto: [...]dmarc.monitor.x@sendloop.com; ruf=mailto:dmarc.monitor.x@sendloop.com; sp=quarantine; fo=1; pct=100; ri=86400; adkim=s; aspf=s;"
```

**Comment by jbusuttil** [comment]
```
SpamAssassin Server version 4.0.0
  running on Perl 5.36.0
  with SSL support (IO::Socket::SSL 2.081)
  with zlib support (Compress::Zlib 2.106)
```

`domain=meetup.com;v=DMARC1; p=reject; pct=100; rua=mailto: [...]dmarc-reports@bendingspoons.com; sp=reject;.`

**Comment by msimerson** [comment]
For anyone else perusing these, note that SpamAssassin is injecting the ` [...]` nonsense into the log entry.

**Comment by sfrothwell** [comment]
SpamAssassin version 4.0.0
  running on Perl version 5.36.0
SpamAssassin Server version 4.0.0
  running on Perl 5.36.0
  with SSL support (IO::Socket::SSL 2.081)
  with zlib support (Compress::Zlib 2.106)

domain=yeehaa.fr
v=DMARC1; p=reject; rua=mailto:dmarc@yeehaa.fr; ruf=mailto:dmarc@yeehaa.fr; 1; adkim=r; aspf=r; rf=afrf; sp=reject; fo=0

**Comment by mfichtner** [comment]
Invalid DMARC record logged by SpamAssassin 4.0.0:
```
domain=kh-karlsruhe.de;v=DMARC1; p=none;.
```
dig +short txt _dmarc.kh-karlsruhe.de
```
v=DMARC1; p=none;.
```

**Comment by galosandras** [comment]
As requested in the mail.log:

```
May 12 14:38:49 ... spamd[1394102]: invalid DMARC record, please post this message to
May 12 14:38:49 ... spamd[1394102]: \thttps: [...]//github.com/msimerson/mail-dmarc/issues/39
May 12 14:38:49 ... spamd[1394102]: \tdomain=tornasport.hu;v=DMARC1;p=reject;sp=reject;pct=90;adkim=r;aspf=
```
```
# opendmarc -V
opendmarc: OpenDMARC Filter v1.4.2
	SMFI_VERSION 0x1000001
	libmilter version 1.0.1
	Active code options:
		WITH_SPF
		WITH_SPF2
# spamd -V
SpamAssassin Server version 4.0.1
  running on Perl 5.36.0
  with SSL support (IO::Socket::SSL 2.081)
  with zlib support (Compress::Zlib 2.106)

```

**Comment by catap** [comment]
as requested in the logs:

```
May 24 12:46:10 mx1 spampd[57405]: invalid DMARC record, please post this message to
May 24 12:46:10 mx1 spampd[57405]:  https: [...]//github.com/msimerson/mail-dmarc/issues/39
May 24 12:46:10 mx1 spampd[57405]:  domain=antonioabate.info;v=DMARC1;p=none;p
May 24 12:46:10 mx1 spampd[57405]: invalid DMARC record, please post this message to
May 24 12:46:10 mx1 spampd[57405]:  https: [...]//github.com/msimerson/mail-dmarc/issues/39
May 24 12:46:10 mx1 spampd[57405]:  domain=antonioabate.info;v=DMARC1;p=none;p
```
