### ISSUE TITLE
Change of behaviour?

### ISSUE THREAD

**Issue by marcbradshaw** [msimerson/mail-dmarc#41]
I have just merged the latest master into my branch and notice a change in behaviour.

Previously, a DKIM pass and SPF softfail resulted in an overall DMARC pass, this has changed to a DMARC fail.

Before
`````
Authentication-Results: test.module;
    dkim-adsp=pass (ADSP policy from marcbradshaw.net);
    dkim=pass (1024-bit rsa key) header.d=marcbradshaw.net header.i=@marcbradshaw.net header.b=DU/QdEi3;
    dkim=pass (2048-bit rsa key) header.d=1e100.net header.i=@1e100.net header.b=aIL04w54;
    dmarc=pass header.from=marcbradshaw.net;
    iprev=fail policy.iprev=123.123.123.123 (NOT FOUND);
    spf=softfail smtp.mailfrom=marc@marcbradshaw.net smtp.helo=bad.name.google.com;
    x-ptr=fail x-ptr-helo=bad.name.google.com x-ptr-lookup=
Received-SPF: softfail (marcbradshaw.net: Sender is not authorized by default to use 'marc@marcbradshaw.net' in 'mfrom' identity, however domain is not currently prep    ared for false failures (mechanism '~all' matched)) receiver=test.module; identity=mailfrom; envelope-from="marc@marcbradshaw.net"; helo=bad.name.google.com; client-i    p=123.123.123.123
`````

After
`````
Authentication-Results: test.module;
    dkim-adsp=pass (ADSP policy from marcbradshaw.net);
    dkim=pass (1024-bit rsa key) header.d=marcbradshaw.net header.i=@marcbradshaw.net header.b=DU/QdEi3;
    dkim=pass (2048-bit rsa key) header.d=1e100.net header.i=@1e100.net header.b=aIL04w54;
    dmarc=fail (p=none) header.from=marcbradshaw.net;
    iprev=fail policy.iprev=123.123.123.123 (NOT FOUND);
    spf=softfail smtp.mailfrom=marc@marcbradshaw.net smtp.helo=bad.name.google.com;
    x-ptr=fail x-ptr-helo=bad.name.google.com x-ptr-lookup=
Received-SPF: softfail (marcbradshaw.net: Sender is not authorized by default to use 'marc@marcbradshaw.net' in 'mfrom' identity, however domain is not currently prep    ared for false failures (mechanism '~all' matched)) receiver=test.module; identity=mailfrom; envelope-from="marc@marcbradshaw.net"; helo=bad.name.google.com; client-i    p=123.123.123.123
`````

**Comment by msimerson** [comment]
That "DMARC passes if either SPF or DKIM is aligned" is covered by [this test](https://github.com/msimerson/mail-dmarc/blob/master/t/04.PurePerl.t#L326). I wonder if this is related to PR #36 throwing an exception, and if merging that made any difference.

**Comment by marcbradshaw** [comment]
Ok, have done some more digging and it seems this is a symptom of another bug.  The message in question has 2 DKIM signatures, one aligned and one not.
The failure is happening because the aligned signature is being lost somewhere, and so we have a non aligned signature and a dkim fail rightly creating a dmarc fail.

Still digging.....

**Comment by marcbradshaw** [comment]
Yeah, that's broken, the second signature overwrites the first, bug introduced in PR #35

**Comment by msimerson** [comment]
I'm still not sure how you're getting that result. I've added another set of [test cases](https://github.com/msimerson/mail-dmarc/commit/3471955decc87851bc36639d59a776dde96c6812) that add successive DKIM results and then retrieve them both. So the ability to add as many DKIM sigs as are found is definitely working, in **some** cases. Adding a test case that covers this would be very helpful.

**Comment by marcbradshaw** [comment]
See https://gist.github.com/marcbradshaw/baa88687b785b30e648d
