### ISSUE TITLE
v1.20150222 doesn't seem to include recent changes

### ISSUE THREAD

**Issue by rjbs** [msimerson/mail-dmarc#51]
From the changelog in master:

```
1.20150222 2015-02-22 America/Los_Angeles

 - tolerate missing SPF auth type scope
 - initialized config file first (was non-deterministic)
```

…but [a comparison of the last two releases](https://metacpan.org/diff/file?target=MSIMERSON/Mail-DMARC-1.20150222/&source=MSIMERSON/Mail-DMARC-1.20150211/#lib/Mail/DMARC/Base.pm) doesn't show this change.  There is no `sort` present, and get_config can still return a filename instead of a Config::Tiny object.

The code in git looks correct, so I'm not sure what happened.  I did a dzil build on master (38ad62d) and the changes to `Mail::DMARC::new` and `Mail::DMARC::Base::get_config` were there.  I really don't know what happened, but the released code doesn't seem to match the repo or the changelog.

**Comment by msimerson** [comment]
Hmm, I'm aware that change is not in that release, because I didn't merge it until *after* the release. The fact that it snuck into Changes is slightly surprising to me, but I expect some human error is to blame.

**Comment by msimerson** [comment]
PS: I'll roll another release soon, I don't think this change is in that release either "missing scope in SPF auth results," and there's another one that's not quite a PR  yet.

**Comment by rjbs** [comment]
Weird.  You say you didn't merge it until after the release, but the "v1.20150222" commit is on 38ad62d, which is the great-grandchild of 13a119c, which includes the merge.  The intervening commit is the one that updates the changelog.  I have nothing more than "weird," I guess.  I look forward to the next release!

**Comment by msimerson** [comment]
Well, I do believe they were committed on the same day, but not necessarily on the same computer, so while the changes were time-linear, the order replayed in the public repo isn't necessarily.
