### ISSUE TITLE
Sub domain reporting at policy level domain.

### ISSUE THREAD

**Issue by marcbradshaw** [msimerson/mail-dmarc#59]
@tomkicamp mentioned this one in relation to another issue yesterday.

> I think I've seen a surfeit of subdomain reporting from (provider). In other words, more than expected. It's up to a bit of interpretation in the spec itself, but the largest providers behave this way: an aggregate report ought to be generated for the domain where the policy is held, only.  Subdomains seen in From headers, for which there is no explicit DMARC record at that level, are reported up in the policy_domain level.

So, a report for sub.example.com could be rolled up into the report for example.com, removing the need for individual reports for the domain and all of its sub domains.

**Comment by tomkicamp** [comment]
Right, with this format of report record as example, where the policy domain is fastmail.com, but when mail01.fastmail.com is seen in the From header, (where there is no explicit DMARC record at the mail01.fastmail.com level), the data is reported in the fastmail.com report rather than generating a separate report for mail01.fastmail.com:

```
...
  <policy_published>
    <domain>fastmail.com</domain>
...
  <record>
    <row>
      <source_ip>123.121.221.111</source_ip>
      <count>1</count>
      <policy_evaluated>
        <disposition>reject</disposition>
        <dkim>fail</dkim>
        <spf>fail</spf>
      </policy_evaluated>
    </row>
    <identifiers>
      <header_from>mail01.fastmail.com</header_from>
    </identifiers>
    <auth_results>
      <dkim>
        <domain>test.agari.edu</domain>
        <result>none</result>
      </dkim>
      <spf>
        <domain>test.agari.edu</domain>
        <result>none</result>
      </spf>
    </auth_results>
  </record>
  <record>
```
