### ISSUE TITLE
confusing/inexact comment

### ISSUE THREAD

**Issue by qzrrbz** [msimerson/mail-dmarc#69]
seeing this in 1.20150317, Mail::DMARC::Base.pm, line 236:

    # You need Perl 5.01 or later at lib/Mail/DMARC/DNS.pm line 83.

ah, there isn't such a thing in this distro.  where should this comment actually point?

thanks!

**Comment by msimerson** [comment]
What version of perl are you running?

**Comment by qzrrbz** [comment]
5.16.3
