### ISSUE TITLE
Extra fields in XML aggregate report

### ISSUE THREAD

**Issue by marcbradshaw** [msimerson/mail-dmarc#74]
The following fields are not defined in the XML schema for aggregate reports (http://dmarc.org/dmarc-xml/0.1/rua.xsd).

record->identifiers->envelope_from
record->auth_results->dkim->selector
record->auth_results->spf->scope

This is causing reports to fail when validated against the schema.

What will be the impact, if any, of removing these fields from the generated reports?

tagging: @msimerson for input

**Comment by msimerson** [comment]
That XML schema is out of date. See the one in the [latest version of the draft](https://tools.ietf.org/html/rfc7489) which has the envelope_from present, the DKIM selector, and SPF scope.
