### ISSUE TITLE
Incorrect handling of Internationalized Domain Names when checking public suffix list

### ISSUE THREAD

**Issue by marcbradshaw** [msimerson/mail-dmarc#78]
Internationalized domain names are failing the public suffix list check.

For example, .政务 which translates to punycode .xn--zfr164b

Domains in the psl are utf-8 rather than punycode, fixes are to read in the psl in a utf safe way, and convert incoming domain names from punycode to unicode before checking.

My current fix brings in a dependency of Net::IDN::Encode, would appreciate thoughts on the best way to approach this. @msimerson 

https://github.com/fastmail/mail-dmarc/commit/1ba5b44d6f66f4f6eb735bbdde534f4a6b150ee3

**Comment by msimerson** [comment]
I just checked where I did another project (wrangling new TLDs) and I used Net::IDN::Encode there and it worked swimmingly. I think you're definitely on the right track.
