### ISSUE TITLE
Tests use live configuration when run outside of distzilla

### ISSUE THREAD

**Issue by marcbradshaw** [msimerson/mail-dmarc#82]
Create a build using dzil build
cd to the build directory,
run perl Makefile.pl && make test

If there is a live configuration installed then the tests run against this rather than the configuration in t/, possibly resulting in dmarc records being written to the database.

Quick and dirty workaround is to copy the test config down to the build directory, but a longer term fix is probably a good idea.

**Comment by msimerson** [comment]
See the changes I just added to t/17.  Basically, in your test file(s), do this:

````
$dmarc->config('t/mail-dmarc.ini');
````

A better solution might be to set an ENV variable in t/* and then have Base.pm automatically load the t/mail-dmarc.ini file when that variable is set.

**Comment by msimerson** [comment]
closing as abandoned/inactive.
