### ISSUE TITLE
Public Suffix List, use of ICANN and PRIVATE sections

### ISSUE THREAD

**Issue by marcbradshaw** [msimerson/mail-dmarc#83]
We currently search both the ICANN and PRIVATE sections of the psl, the DMARC section of the [psl uses document](https://wiki.mozilla.org/Public_Suffix_List/Uses) states that we should probably ignore the private section, but notes that the DMARC spec doesn't specify.

@msimerson, what are your thoughts on this?

**Comment by msimerson** [comment]
I'm inclined to agree with the PSL publishers.

**Comment by marcbradshaw** [comment]
Mozilla provide both, in sections. I have no strong opinion, can see arguments for both ways.
