### ISSUE TITLE
CPAN release

### ISSUE THREAD

**Issue by marcbradshaw** [msimerson/mail-dmarc#95]
Hi Matt,

Could I request a new CPAN release, please and thank you. :)

**Comment by msimerson** [comment]
Happy to. However, a couple things should happen first:

### release todo

1. [ ] `dzil test` needs to pass. I've fixed this in #96 
2. [ ] the Changes file needs to be updated

**Comment by msimerson** [comment]
If you could get the Changes file updated, I could get it released today. Else, it'll have to wait until next week, after I've caught up on other tasks.

**Comment by msimerson** [comment]
````
[UploadToCPAN] registering upload with PAUSE web server
[UploadToCPAN] POSTing upload for Mail-DMARC-1.20160612.tar.gz to https://pause.perl.org/pause/authenquery
[UploadToCPAN] PAUSE add message sent ok [200]
[Git::Commit] WARNING: No changes listed under 1.20160612 in Changes
[Git::Commit] Committed Changes dist.ini
[Git::Tag] Tagged v1.20160612
[Git::Push] pushing to origin
````
