### ISSUE TITLE
The link to the qpsmtpd DMARC pluginin the wiki does not work

### ISSUE THREAD

**Issue by brianread108** [msimerson/mail-dmarc#97]
The wiki gives a link for the qpsmtpd plugin, but it does not work:

https://github.com/qpsmtpd-dev/qpsmtpd-dev/blob/master/plugins/dmarc

**Comment by msimerson** [comment]
Please provide a link to the page where that link was found. Or update that page with he updated URL: `https://github.com/smtpd/qpsmtpd/blob/master/plugins/dmarc`

**Comment by brianread108** [comment]
This is the link to the Wiki:

https://github.com/msimerson/mail-dmarc/wiki

I've edited that one (I did not realise I could edit !)

However also the link in the section "Email Senders and Receivers" is also not working, this is what I get:

https://github.com/qpsmtpd-dev/qpsmtpd-dev/commit/b8df80d3

**Comment by msimerson** [comment]
For anyone that notices specific issues like this in the future, the qpsmtpd-dev repo was merged into qpsmtpd, so just strip off the -dev suffix. Also, the qpsmtpd-dev github user was deprecated and the main repo was renamed to 'smtpd'. Fixing those two items restores any of those old links.
