### ISSUE TITLE
loop in dmarc_send_report

### ISSUE THREAD

**Issue by bigio** [msimerson/mail-dmarc#99]
I received some mails from sp-assu.fr and other domains that have the same rua; the rua seems not legit, Google replies to dmarc_send_report with error 450 and dmarc_send_report goes in a loop.
------------------------------------------------------------------------------------------------------------------------------
$ host -ttxt sp-assu.fr
sp-assu.fr descriptive text "v=spf1 include:spf.sendinblue.com mx ~all"
$ host -ttxt _dmarc.sp-assu.fr
_dmarc.sp-assu.fr descriptive text "v=DMARC1\; p=none\; sp=none\; rua=mailto:dmarc@mailinblue.com!10m\; ruf=mailto:dmarc@mailinblue.com!10m\; rf=afrf\; pct=100\; ri=86400"
------------------------------------------------------------------------------------------------------------------------------
ID:     12878
Domain: sp-assu.fr
rua:    mailto:dmarc@mailinblue.com!10m
getting MX for mailinblue.com
delivering message to dmarc@mailinblue.com, via aspmx.l.google.com
RCPT TO dmarc@mailinblue.com rejected
        450 4.2.1 The user you are trying to contact is receiving mail at a rate that
4.2.1 prevents additional messages from being delivered. Please resend your
4.2.1 message at a later time. If the user is able to receive mail at that
4.2.1 time, your message will be delivered. For more information, please
4.2.1 visit
4.2.1  https://support.google.com/mail/answer/6592 n63si4220274wme.21 - gsmtp
------------------------------------------------------------------------------------------------------------------------------

**Comment by msimerson** [comment]
What I see there is exactly whats supposed to happen.

`rua: mailto:dmarc@mailinblue.com!10m` looks legit to me. 

dmarc_send_report is supposed to retry (loop?) when it can't deliver a report.

**Comment by bigio** [comment]
dmarc_send_report retries when it can't deliver a report but, in this case, Google always replies with "450 4.2.1 ....", dmarc_send_report retries and the process never ends.

**Comment by msimerson** [comment]
450 is a temporary error. dmarc_send_report is **supposed** to keep retrying. That's how SMTP works.

**Comment by bigio** [comment]
Sure, but if you continue to try after 5 seconds (or even more) you will never come to an end iff the error is "4.2.1 rate limit".
Smtp servers have an expire option to remove email that, otherwise, would be stuck in the queue forever.

**Comment by msimerson** [comment]
> Smtp servers have an expire option to remove email that otherwise, would be stuck in the queue forever.

You seem to be assuming that dmarc_send_report does not.

I'm not saying there is no problem, simply that you haven't demonstrated or showed anything that proves there is.
